server:
  # 指定端口号
  port: 20000
  servlet:
    context-path: /register
# 无效
#spring:
#  application:
#    name: spring-cloud-netflix-eureka
#  profiles:
#    active: dev
#  cloud:
#    config:
#      uri: http://localhost:8888/config/
#      label: master